### PR TITLE
Further improve support for Razer Synapse v4

### PR DESCRIPTION
**Pull request by PromoFaux**
Added a check to reset the offset and start reading from the beginning if the file size has decreased/file has been rotated.

### CODE REVIEW

**Comment by BarRaider** [comment]
Hey, 
Can you make a thorough test of this version and ensure there are no more bugs you can find?
I want to push a final version with good quality and can't test this myself as I don't have the hardware.

**Comment by PromoFaux** [comment]
Yeah no worries, I've been running this code as is since yesterday morning, and it appears to be surviving the log rotations - pretty sure I have caught everything now - but will run it for a couple of days to make sure it's stable

**Comment by PromoFaux** [comment]
@BarRaider - after some brute forcing to make Synapse rotate the log file, I've added some detailed comments that explain what appears to be the parameters we are working with when it comes to deciding whether or not the log file has rotated.

I know you don't have any Razer hardware, but maybe you can review this based purely on logic.

Initially I was going to keep an eye on the filename that we are currently reading, and if that differs from the previous filename, then assume that we have rotated to the next file - however, as you can see, that stops once we get to log file 5, so it seems the only option here is to check the current file size against the last position we read to... if the size is lower, we assume it's rotated.

On a long running Synapse 4 installation will probably _always_ be reading from `background-manager5.log`. I say probably, because all of this is just based on trial and error!

**Comment by BarRaider** [comment]
What about the last modified date? I'm assuming the active file has the most recent modified date? Regardless of its number

**Comment by PromoFaux** [comment]
Sometimes it can get into a state where lower numbers have a more recent modified date than the active file - though that usually settles out after a minute, and this example is probably an extreme edge case due to the aforementioned brute forcing.

image

Even if we go by latest modified date over highest filename - we still need to reset `lastMaxOffset` to 0 if it's detected that it is larger than the stream's current length.

I was actually surprised to learn that `StreamReader.BaseStream.Seek()` does not throw an error if you attempt to seek beyond the end of the stream - it just returns no data until the stream is extended. Hence this went unnoticed until I'd been running it a while after you packaged 1.6.4.

As the code is - the active file will always be selected on each run of RefreshStats, and we will either continue from where we left off on the last run, or start the file again depending on it's length. 


Really, even taking into account file rotation, I would have expected the active file to have always been `background-manager.log`, with the higher file numbers being older copies - at least that's what I'm used to seeing, but who knows what goes on in the minds of Razer's development team 😏

**Comment by PromoFaux** [comment]
I think I'm confident enough to say this is stable now - deleted all logs yesterday and then started from `background-manager.log` and it has now rotated all the way through to 5, and then a couple iterations of 5 since it got there. Plugin has been reporting accurate stats throughout

**Comment by PromoFaux** [comment]
@BarRaider - still working as expected, no bugs, crashes or the like detected so far.

Slightly different - is there a repo for https://docs.barraider.com/ ? If so, I could add some words to that to cover this component if you like

**Pull request merged**
